# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'arnold_app_v2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for arnold_app_v2

  target 'arnold_app_v2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'arnold_app_v2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'arnold_app_v2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for arnold_app_v2-tvOS

  target 'arnold_app_v2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end